### ISSUE TITLE
Rusty-secrets version in package.json should point to a specific Git release/tag

### ISSUE THREAD

**Issue by emkll** [freedomofpress/sunder#108]
# Feature Request

## Description

[package.json](https://github.com/freedomofpress/sunder/blob/master/package.json#L115) points to a [rusty-secrets release](https://github.com/SpinResearch/rustysecrets-node/releases) that is not or no longer available. [NPMJS](https://www.npmjs.com/package/rusty-secrets) reports that 20 releases are available (presumably 0.0.13 is one of them).

## User Stories

As a Sunder user, I would like to easily inspect the source code of the underlying libraries.

**Comment by conorsch** [comment]
We should test an upgrade to the latest-and-greatest, which is 0.3.0 as of this writing: https://github.com/SpinResearch/rustysecrets-node/releases/tag/v0.3.0
