### ISSUE TITLE
Identify some "easy" bugs/feature requests for newcomers

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/sunder#112]
As part of publicizing Sunder a bit more, we should identify easy issues for newcomers to work on, and label them with "easy" or similar.

**Comment by liliakai** [comment]
I tagged a few. Mostly straight foward front-end ui tweaks: https://github.com/freedomofpress/sunder/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy

The docs tag might also be a good starting place for folks who want to contribute but aren't coding-inclined: https://github.com/freedomofpress/sunder/issues?q=is%3Aissue+is%3Aopen+label%3Adocs
