### ISSUE TITLE
During recovery, allow select multiple files at once

### ISSUE THREAD

**Issue by koenaad** [freedomofpress/sunder#122]
# Feature Request

## Description

When selecting the files to recover from, allow the user to select multiple files at once. Importing shares one-by-one can be tedious.

Possible solutions:
- allow to select multiple files
- shares may be grouped in one folder, allow to import a complete folder at once

**Comment by eloquence** [comment]
Totally agree, this is a nuisance in the current UI. Do you have any interest in taking this one on yourself?

**Comment by koenaad** [comment]
Yeah, maybe. I'm new to this project and the used framework, but I am willing to look into some of the easy issues and contribute some work.

I got here via the Freedom of Press twitter and wanted to list some of the issues I encountered while testing. I hope it's not too much if I open multiple issues in such a short time.

**Comment by eloquence** [comment]
On the contrary, file away! These are very useful observations, thank you. :) Starting with an "easy" issue is indeed a good way to go, and if you get stuck, feel free to just post questions in the issue you're working on and we'll try to help.

**Comment by eloquence** [comment]
@koenaad Just a note - if you would like to take on this or any other Sunder-related issues and have any questions about the architecture or code, the maintainer team can now also be found on Gitter chat: https://gitter.im/freedomofpress/sunder

**Comment by conorsch** [comment]
Resolved by #141.
