### ISSUE TITLE
Invalid shares passed to the recovery function

### ISSUE THREAD

**Issue by liliakai** [freedomofpress/sunder#131]
# Bug

## Description

It is possible to select a malformed share plus a quorum of valid shares such that both the valid and invalid shares are passed along to rusty-secrets for processing, which fails.

## Steps to Reproduce

From the Recover screen, load an invalid share file (e.g. Beautiful Duck.png).
Then, without removing the first file, load a quorum of valid shares (e.g. secret-shard-{1-5}.txt).

### Actual Behavior

The Recover button appears, but clicking it causes the invalid shares to be passed along to the recover function, which fails.

### Expected Behavior

The Recover button does not appear as long as there are invalid shares present.

**Comment by abhn** [comment]
I'd like to work on this. I think I understand the issue and I'll work on a fix.

**Comment by conorsch** [comment]
@abhn Thanks for your interest. :slightly_smiling_face: A PR would be very welcome on this front. If you have any questions, don't hesitate to comment here, or discuss in the [Sunder Gitter channel](https://gitter.im/freedomofpress/sunder).
