### ISSUE TITLE
Destroy all Makefiles?

### ISSUE THREAD

**Issue by liliakai** [freedomofpress/sunder#149]
Building and testing this project can be a little confusing at first, due to the mixed use of `make` and `npm` as command-line task runners. In many cases, the Makefile is actually just calling out to npm in order to run scripts defined in package.json.

Good old make, though powerful, is not exactly in vogue in the world of modern javascript and electron-based projects.  I feel pretty confident that we could remove the use of make and Makefiles from the project with a bit of effort, and rely solely on npm and a handful of shell scripts in /tools for building and testing. This might make the project infrastructure a bit more approachable to new devs.

Thoughts?

**Comment by conorsch** [comment]
No concerns, @liliakai! The dev env is far from ergonomic, so feel free to shove tooling around to make it more friendly to contributors.

**Comment by liliakai** [comment]
I take back what I said about make. I relied on it partially to achieve dockerization of the test suite and CI. I reserve the right to revisit this decision in the future but for now, make shall live on! 🤓
