### ISSUE TITLE
[RFE] Save all option/button

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/sunder#88]
# Feature Request

## Description

There should be a "Save all" button to save all the secrets.

## User Stories

I am user and I don't want to manually click and download all the 9 different shared secret files. That is too many clicks.

**Comment by koenaad** [comment]
Hi, I'm looking into this. Got a solution which asks the user to select a directory and saves all the shares there.
I'll clean it up and PR it in the next few days.
