### ISSUE TITLE
Clearly document dependency on RustySecrets

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/sunder#90]
# Feature Request

## Description

The project documentation should link out to the repositories for the underlying RustySecrets code: 
  * https://github.com/SpinResearch/RustySecrets
  * https://github.com/SpinResearch/rustysecrets-node

Preferably this information would be in the README, as well as anywhere else developer-oriented documentation lands.

## User Stories

As a developer, I want to explore the underlying libraries doing the heavy lifting, particularly in high-security contexts such as cryptographic implementations.

**Comment by liliakai** [comment]
These links are in the README. I have just pushed a `docs` branch that fixes links in the docs as well.
