### ISSUE TITLE
Should we be using asar archives for packaging?

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/sunder#92]
# Feature request

## Description

When building Linux Debian packages, this message displays prominently:

```
Rebuilding native production dependencies for linux:x64
Warning: Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
Packaging for linux x64 using electron 1.7.11 to dist/linux-unpacked
Building deb
```

Should we make changes here? Further research required.

## User Stories

As a developer, I tend to pay attention to scary messages by other developers, even when they're ambiguously worded.

**Comment by msheiny** [comment]
From https://electronjs.org/docs/tutorial/application-packaging:

> To mitigate issues around long path names on Windows, slightly speed up require and conceal your source code from cursory inspection, you can choose to package your app into an asar archive with little changes to your source code.

I honestly think it would be cool if we package our app into a Windows binary and serve it up via [chocolatey](https://chocolatey.org/) . I don't volunteer to do that now though so I'm not making a ticket :)

**Comment by conorsch** [comment]
> it would be cool if we package our app into a Windows binary

This was discussed energetically back in the early stages of the project. We decided _not_ to support Windows, simply because we didn't have the physical hosts around to perform adequate testing. Our plan was to ship early with fewer platforms supported and keep the door open for more platforms down the road if there's interest. We kinda fell down on the "ship early" part, but kept the "fewer platforms supported". :slightly_smiling_face:

**Comment by liliakai** [comment]
Is there any technical reason not to use asar, even if only to silence the scary warning?

Some things that can be problematic with asar:
* prodigious use of absolute paths
* modifying files in the app directory
* changing the working directory
* use of node api calls [with caveats for asar]( https://electronjs.org/docs/tutorial/application-packaging#limitations-of-the-node-api):
  * child_process.exec
  * child_process.spawn
  * child_process.execFile
  * child_process.execFileSync
  * fs.open
  * fs.openSync
  * fs.stat
