### ISSUE TITLE
Linux build fails on macOS

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/sunder#98]
# Bug

## Description

The new Dockerized Linux build pipeline fails with an error near the end of the build process.
This seems like it would be an issue on any host platform, but I have only encountered it on macOS.

## Steps to Reproduce

1. `make build`

### Expected Behavior

Build process succeeds and a new `.deb` package is stored in `dist/`, as per the build instructions in the README.

### Actual Behavior

Build fails with error message:

```
Error: Please specify author 'email' in the application package.json

See https://docs.npmjs.com/files/package.json#people-fields-author-contributors

It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://www.electron.build/configuration/linux).
```

## Comments

Fix seems pretty clear from electron-builder's error message.

**Comment by conorsch** [comment]
Hmm, unable to reproduce the failure on macOS. Running 10.13.3. Software versions:

```
$ node --version
v7.10.0
$ npm --version
4.2.0
$ docker --version
Docker version 17.12.0-ce, build c97c6d6
```

Admittedly those versions are out of date with what we recommend in the README, so I'll try again following the docs carefully. The node/npm versions should not affect the containerized build, however, so it looks like I'm having trouble reproducing the issue.

**Comment by conorsch** [comment]
Ah, got it! The error described above was indeed listed in the scrollback. The `make build` command exited zero, which is puzzling, but the build did indeed fail: no `*.deb` package was created.

**Comment by conorsch** [comment]
Confirming that `make clean && make build` fails on a Linux host, with the same error message. Fortunately the build command fails with a non-zero exit code this time. 

Looks like the problem did indeed come in via #87, and wasn't caught before merge. 

```
make
